In [212]:
import numpy as np
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer


In [213]:
Books=pd.read_csv("data.csv")
print(Books.head())
print(Books.info())

          isbn13      isbn10           title subtitle  \
0  9780002005883  0002005883          Gilead      NaN   
1  9780002261982  0002261987    Spider's Web  A Novel   
2  9780006163831  0006163831    The One Tree      NaN   
3  9780006178736  0006178731  Rage of angels      NaN   
4  9780006280897  0006280897  The Four Loves      NaN   

                           authors                     categories  \
0               Marilynne Robinson                        Fiction   
1  Charles Osborne;Agatha Christie  Detective and mystery stories   
2             Stephen R. Donaldson               American fiction   
3                   Sidney Sheldon                        Fiction   
4              Clive Staples Lewis                 Christian life   

                                           thumbnail  \
0  http://books.google.com/books/content?id=KQZCP...   
1  http://books.google.com/books/content?id=gA5GP...   
2  http://books.google.com/books/content?id=OmQaw...   
3  http://books.go

In [214]:
#Data preprocessing 
# Remove duplicates'
print(Books.duplicated().sum())
Books=Books.drop_duplicates(subset='title')
# Select important columns
#isbn13
#title	
#authors	
#categories	
#description
#average_rating

Books=Books[['isbn13','title','authors','categories','description']]

# Processsing null values
print(Books.isna().sum())
#remove the null values as its counts are not bigger
Books=Books.dropna()
Books.count()
Books.head()
Books = Books.reset_index()


0
isbn13           0
title            0
authors         66
categories      91
description    243
dtype: int64


In [215]:
# Remove spaces between author name and categories name
Books['authors']=Books['authors'].str.replace(" ",'')

Books['authors']

0                              MarilynneRobinson
1                  CharlesOsborne;AgathaChristie
2                             StephenR.Donaldson
3                                  SidneySheldon
4                              CliveStaplesLewis
                          ...                   
6057                                HermannHesse
6058                                 RobinSharma
6059    SriNisargadattaMaharaj;SudhakarS.Dikshit
6060                  GeorgWilhelmFriedrichHegel
6061                        HelenaGrice;TimWoods
Name: authors, Length: 6062, dtype: object

In [216]:
Books['categories']=Books['categories'].str.replace(" ",'')
Books['categories']

0                          Fiction
1       Detectiveandmysterystories
2                  Americanfiction
3                          Fiction
4                    Christianlife
                   ...            
6057              Adventurestories
6058                Health&Fitness
6059                    Philosophy
6060                       History
6061             LiteraryCriticism
Name: categories, Length: 6062, dtype: object

In [217]:
Books['tags']=Books['categories']+"."+Books['description']+Books['authors']
Books['tags'][10]
Books=Books.drop(['categories','description','authors'],axis=1)
Books

,index,isbn13,title,tags
0,0,9780002005883,Gilead,Fiction.A NOVEL THAT READERS and critics have ...
1,1,9780002261982,Spider's Web,Detectiveandmysterystories.A new 'Christie for...
2,2,9780006163831,The One Tree,Americanfiction.Volume Two of Stephen Donaldso...
3,3,9780006178736,Rage of angels,"Fiction.A memorable, mesmerizing heroine Jenni..."
4,4,9780006280897,The Four Loves,Christianlife.Lewis' work on the nature of lov...
...,...,...,...,...
6057,6803,9788173031014,Journey to the East,Adventurestories.This book tells the tale of a...
6058,6804,9788179921623,The Monk Who Sold His Ferrari: A Fable About F...,Health&Fitness.Wisdom to Create a Life of Pass...
6059,6805,9788185300535,I Am that,Philosophy.This collection of the timeless tea...
6060,6808,9789027712059,The Berlin Phenomenology,History.Since the three volume edition ofHegel...


In [218]:
from nltk.stem.porter import PorterStemmer
stemmer=PorterStemmer()

def stem(text):
    y=[]
    for i in text.split():
        y.append(stemmer.stem(i))

    result=" ".join(y)
    return result
        

In [219]:
# Apply stem function to our tag column
Books['tags']=Books['tags'].apply(stem)
Books['tags']

0       fiction.a novel that reader and critic have be...
1       detectiveandmysterystories.a new 'christi for ...
2       americanfiction.volum two of stephen donaldson...
3       fiction.a memorable, mesmer heroin jennif -- b...
4       christianlife.lewis' work on the natur of love...
                              ...                        
6057    adventurestories.thi book tell the tale of a m...
6058    health&fitness.wisdom to creat a life of passi...
6059    philosophy.thi collect of the timeless teach o...
6060    history.sinc the three volum edit ofhegel' phi...
6061    literarycriticism.thi is a jubil and reward co...
Name: tags, Length: 6062, dtype: object

In [220]:
cv =CountVectorizer(max_features=1000,stop_words='english')
vectors=cv.fit_transform(Books['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(6062, 1000))

In [221]:
cv.get_feature_names_out()

array(['000', '10', '100', '15', '20', '25', '50', 'abandon', 'abil',
       'abov', 'accept', 'access', 'acclaim', 'accompani', 'account',
       'achiev', 'act', 'action', 'actual', 'ad', 'adam', 'addit',
       'address', 'adult', 'adventur', 'advic', 'affair', 'africa',
       'african', 'aft', 'age', 'agent', 'ago', 'alien', 'allow',
       'altern', 'alway', 'america', 'american', 'analysi', 'ancient',
       'angel', 'ani', 'anim', 'ann', 'anoth', 'answer', 'antholog',
       'anyon', 'anyth', 'appear', 'approach', 'area', 'argu', 'armi',
       'arriv', 'art', 'artist', 'ask', 'aspect', 'attack', 'attempt',
       'attent', 'attract', 'author', 'authors', 'autobiography', 'avail',
       'award', 'away', 'babi', 'background', 'bad', 'base', 'battl',
       'bear', 'beauti', 'becam', 'becaus', 'becom', 'befor', 'began',
       'begin', 'belief', 'believ', 'belov', 'best', 'bestsel', 'better',
       'big', 'biographi', 'biography', 'birth', 'bizarr', 'black',
       'blood', 'bl

In [222]:
vectors[0]
vectors.shape

(6062, 1000)

In [223]:
# Cosine distance
from sklearn.metrics.pairwise import cosine_similarity
distance_matrix=cosine_similarity(vectors)
print(distance_matrix)

[[1.         0.03720327 0.         ... 0.30903983 0.10291616 0.        ]
 [0.03720327 1.         0.040996   ... 0.10347562 0.11834527 0.        ]
 [0.         0.040996   1.         ... 0.         0.0412393  0.        ]
 ...
 [0.30903983 0.10347562 0.         ... 1.         0.16191735 0.17309693]
 [0.10291616 0.11834527 0.0412393  ... 0.16191735 1.         0.        ]
 [0.         0.         0.         ... 0.17309693 0.         1.        ]]


In [224]:
distance_matrix[1]

array([0.03720327, 1.        , 0.040996  , ..., 0.10347562, 0.11834527,
       0.        ], shape=(6062,))

In [229]:
Book_name=input("Enter name of a book")


idx=Books[Books['title']==Book_name].index[0]
print(idx)
distance=distance_matrix[idx]
print(distance)

Enter name of a book The Trial


545
[0.11433239 0.10846523 0.         ... 0.         0.10910895 0.        ]


In [230]:

rec_books=sorted(list(enumerate(distance)),key=lambda x:x[1],reverse=True)[0:6]



def recommended(lst):
    for i in lst:
        print(Books.iloc[i[0]]['title'])

recommended(rec_books)

The Trial
The Nonexistent Knight & The Cloven Viscount
Thousand Cranes
Age of Iron
Robinson Crusoe
The Grapes of Wrath


In [235]:
Books.to_csv('cleaned_data.csv',index=False)
